output_dir: /output

dataset:
  class: JointDataset
  graphs: [FB15k237, WN18RR, CoDExMedium]
  root: /kg-datasets/

model:
  class: TRIX
  relation_model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
  entity_model_1:
    class: IndNBFNet
    input_dim: 32
    hidden_dims: [32, 32]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
  entity_model_2:
    class: IndNBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes

task:
  name: MultiGraphPretraining
  num_negative: 512
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: AdamW
  lr: 5.0e-4

train:
  gpus: {{ gpus }}
  batch_size: 32
  num_epoch: 10
  log_interval: 800
  batch_per_epoch: 80000
  fast_test: 500
  logger: wandb